all: 
	python3 main.py --fasta seq.fasta --match 5 --mismatch -3 --gapopen -8 --gapext -1 --out seq.tree
test:
	python3 main.py --fasta test_input.fasta --match 5 --mismatch -3 --gapopen -8 --gapext -1 --out seq.tree